export const ADD_SMALLBILL_REQUEST = "ADD_SMALLBILL_REQUEST"
export const ADD_SMALLBILL_SUCESS = "ADD_SMALLBILL_SUCCESS"
export const ADD_SMALLBILL_FAILURE = "ADD_SMALLBILL_FAILURE"

export const FETCH_SMALLBILLS_REQUEST = 'FETCH_SMALLBILLS_REQUEST'
export const FETCH_SMALLBILLS_SUCCESS = 'FETCH_SMALLBILLS_SUCCESS'
export const FETCH_SMALLBILLS_FAILURE = 'FETCH_SMALLBILLS_FAILURE'

export const FETCH_DOC_REQUEST = 'FETCH_DOC_REQUEST'
export const FETCH_DOC_SUCCESS = 'FETCH_DOC_SUCCESS'
export const FETCH_DOC_FAILURE = 'FETCH_DOC_FAILURE'