export const SMALLBILL_CREATION_REQUEST = "SMALLBILL_CREATION_REQUEST"
export const SMALLBILL_CREATION_SUCCESS = "SMALLBILL_CREATION_SUCCESS"
export const SMALLBILL_CREATION_FAILURE = "SMALLBILL_CREATION_FAILURE"