export const CREATE_PARTIE_REQUEST = "CREATE_PARTIE_REQUEST"
export const CREATE_PARTIE_SUCCESS = "CREATE_PARTIE_SUCCESS"
export const CREATE_PARTIE_FAILURE = "CREATE_PARTIE_FAILURE"

export const FETCH_PARTIES_REQUEST = "FETCH_PARTIES_REQUEST"
export const FETCH_PARTIES_SUCCESS = "FETCH_PARTIES_SUCCESS"
export const FETCH_PARTIES_FAILURE = "FETCH_PARTIES_FAILURE"