export const CREATE_COMMODITY_REQUEST = "CREATE_COMMODITY_REQUEST"
export const CREATE_COMMODITY_SUCCESS = "CREATE_COMMODITY_SUCCESS"
export const CREATE_COMMODITY_FAILURE = "CREATE_COMMODITY_FAILURE"


export const EDIT_COMMODITY_REQUEST = "EDIT_COMMODITY_REQUEST"
export const EDIT_COMMODITY_SUCCESS = "EDIT_COMMODITY_SUCCESS"
export const EDIT_COMMODITY_FAILURE = "EDIT_COMMODITY_FAILURE"


export const FETCH_COMMODITIES_REQUEST = "FETCH_COMMODITIES_REQUEST"
export const FETCH_COMMODITIES_SUCCESS = "FETCH_COMMODITIES_SUCCESS"
export const FETCH_COMMODITIES_FAILURE = "FETCH_COMMODITIES_FAILURE"